[versions]
agp = "9.0.0"
core = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
play-feature-delivery = "2.1.0"

[libraries]
core = { group = 'androidx.core', name = "core", version.ref = "core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
play-feature-delivery = { module = "com.google.android.play:feature-delivery", version.ref = "play-feature-delivery" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidDynamicFeature = { id = "com.android.dynamic-feature", version.ref = "agp" }

[bundles]
