plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
}

android {
    namespace = 'org.qtproject.qt.gradlecache'
    compileSdk = 36

    defaultConfig {
        applicationId "org.qtproject.qt.gradle.cache"
        minSdk = 28
    }
}

dependencies {
    implementation libs.core
    implementation libs.appcompat
    implementation libs.material
}
