Version: 2
Include: [
  macos.yaml: [
    "macos-14-x86_64-tests",
    "macos-14-arm64-tests",
    "macos-arm64-developer-build",
  ],
  cmake_platforms.yaml: [
    "ubuntu-24.04-x64",
    "ubuntu-24.04-x64-developer-build",
    "ubuntu-24.04-x64-x11-tests",
    "ubuntu-24.04-x64-developer-build-x11-tests",
  ]
]
Configurations: []
